### ISSUE TITLE
Issue : App unabe to Start 0xC0000142 on Win10

### ISSUE THREAD

**Issue by GregS1000RR** [BazzaCuda/MinimalistMediaPlayerX#51]
Hi, 
I discovered a few weeks ago your great development, which I'm using almost daily on my dev laptop successfully and with pleasure.

Now I'm trying to bring it to work on a fresh installed barebone PC with Win10 Pro.

I have exact config as mentioned: unzipped latest release under C:\MMP, did the install.bat for file association, but when I tried to launch the App, it raises App Error # 0xC0000142 (App unable to start correctly)

Can you help ?
Is there a missing library or framework ?
Thank you 
Regards
Gregory

**Comment by GregS1000RR** [comment]
Add. info : 
 * Win 10 Pro 64Bit (Build 19045)
 *  CPU Celeron J1800 @ 2.4GHz with 8GB RAM
 *  Audio Driver : HdAudio.sys (Microsoft) Ver 10.0.19041
 * Windows Media Player : Works Ok
 *  Media Player Classic    : Works OK (MPC-HC Ver 1.9.11
 *  DirectX (DXDiag say ALL OK)
 *  Run the 'depends.exe'. but the output is hard for me to extract the useful information

Let me know if you want me to try another test SW to figure out what could be missing to make it work ?  

Thank you for your attention
Best Regards

**Comment by BazzaCuda** [comment]
Hi.

Thanks for the extra info. It may be the Celeron processor. The supplied version of libmpv-2.dll is built deliberately for higher-spec machines.

To run MMP you need the following files:
MinimalistMediaPlayer.exe
MediaInfo.dll
libmpv-2.dll
ffmpeg.exe
libeay32.dll
ssleay32.dll

There is a version of libmpv-2.dll which is built specifically for lower-spec processors.
You can get a copy here: https://github.com/BazzaCuda/mpv-winbuild/releases
Specifically, this file: https://github.com/BazzaCuda/mpv-winbuild/releases/download/2024-08-17-a3baf94/mpv-dev-x86_64-20240817-git-a3baf94.7z

It's the "mpv-dev" build for 64-bit x86 processesors which does NOT have the "v3" indicator in the .7z file name.

Out of interest, what's the processor in the machine that you've been successfully using MMP?

**Comment by GregS1000RR** [comment]
Hi, 

Thank you so much for your clear and successfully working reply.

By replacing the libmpv-2.dll it move a step further.

The App is opening, but raise an exception : 

EInvalidOp in module libmpv-2 at 
06A4FE
Invalid Floating Point operation.

I feel sorry to bother you with this.

For the other question : the other machine is already quite old, but still works fine. It's a Asus running under 
Win10 Pro
Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz   2.59 GHz

On this 'working' machine, I'm having Delphi 10.2 and VSC, and many other tools, thus my previous question, could it be that a barebone PC is missing some framework lib's. 

I'm telling this because, once a while I developed an app using ActiveX (yes it's a long time ago :-) on a bare new PC, I had to launch once the MS-Office installer to make it work

Regards
Gregory

**Comment by BazzaCuda** [comment]
Hi Gregory,

My gut feeling is telling me that the libmpv dll won't run on a Celeron processor. The EInvalidOp is the clue. I suspect that Celerons may have a reduced instruction set. I will admit though that I don't have any experience of running on Celeron processors.  I would be surprised if this were due to missing Microsoft libs, although of course one can never be entirely sure as Microsoft software doesn't exactly provide useful error messages.

As I say, my gut feeling is that you're not going to get this running on a Celeron.
The only options I have is between the two versions of libmpv-2.dll: the high-spec "v3" build and the lower-spec one.

There are settings you _could_ add to mpv.conf to manipulate how MPV is operating, but I'm very reluctant to send you down that rabbit hole as I have no idea if that could even be a solution for you. If it was my machine, I think I'd do a quick Google for "MPV on celeron" and see what discussions there have been on the subject and to _very quickly_ decide if I was likely flogging a dead horse persisting with the Celeron.

If the problem ever turns out to be nothing to do with the Celeron then I can only apologize in advance for making that assumption :D

Regards,
Baz.
